version: "3.1"

services:
  db:
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/db/shortcut
    ports:
      - 27017:27017
  web:
    build:
      dockerfile: Dockerfile
      context : ./api
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./api:/app
    command: npm run start
    environment: 
    - MONGO_URI_LOCAL=mongodb://db:27017/test
    restart: on-failure
    depends_on:
      - db
