version: "3.1"

services:
  db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: npm run start
    links:
      - db
    restart: on-failure
    depends_on:
      - db
